version: '2'
services:
  db:
    image: mysql:5.6
    container_name: database
    ports:
     - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=bookManage
   
  web:
    build: ./client
    container_name: web_client
    ports: 
     - 80:3000
    depends_on: 
     - db
    # 一旦コンテナにホストのグローバルIPを渡すための環境変数を設定
    environment:
     - HOST_GLOBAL_IP_ADDRESS=${HOST_GLOBAL_IP}

  server:
    build: ./server
    container_name: web_server
    ports:
     - 5000:5000
    depends_on:
     - db
