version: '2'
services:
  db:
    image: mysql:5.6
    ports:
     - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=app
